### ISSUE TITLE
friend, your project files don't correspond with your documentation？

### ISSUE THREAD

**Issue by jiaxiaogao** [CoderTylor/IoV-SFDL-Swarm-Federated-Deep-Learning#1]

**Comment by CoderTylor** [comment]
In fact, all the codes are modified on the basis of swarm learning framework. You can try the markdown description first:
First, please fellow the Swarm Learning @  https://github.com/HewlettPackard/swarm-learning  to download and setup docker images and evaluation licenses.

All the files used in the experiment are uploaded here, It's quiet mass, I will sort them out later.

**Comment by wkyd** [comment]
您好，我在运行 sudo ./swarm-learning/bin/run-apls --apls-port=5814后出现如下信息：
Unable to find image 'hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/apls:0.3.0' locally
docker: Error response from daemon: Head "https://hub.myenterpriselicense.hpe.com/v2/hpe_eval/swarm-learning/apls/manifests/0.3.0": no basic auth credentials.
See 'docker run --help'.
