### ISSUE TITLE
请问SwarmLearning框架的使用是免费的吗？还是需要购买的呢？

### ISSUE THREAD

**Issue by 1160300315** [CoderTylor/IoV-SFDL-Swarm-Federated-Deep-Learning#2]

**Comment by CoderTylor** [comment]
Currently it is free of charge. It is provided by Hewlett Packard group and can be downloaded and setup according to the url: https://myenterpriselicense.hpe.com/cwp-ui/auth/login. Once download for 6 months free of use

**Comment by 1160300315** [comment]
Thanks!        
            
                
                    
                            
                                
                            
                            
                                jiangxi
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        ---- 回复的原邮件 ***@***.***>发送日期2022年09月06日 21:46 ***@***.***> ***@***.******@***.***>主题Re: [CoderTylor/IoV-SFDL-Swarm-Federated-Deep-Learning] 请问SwarmLearning框架的使用是免费的吗？还是需要购买的呢？ (Issue #2)
Currently it is free of charge. It is provided by Hewlett Packard group and can be downloaded and setup according to the url: https://myenterpriselicense.hpe.com/cwp-ui/auth/login. Once download for 6 months free of use

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/CoderTylor/IoV-SFDL-Swarm-Federated-Deep-Learning/issues/2#issuecomment-1238175358",
"url": "https://github.com/CoderTylor/IoV-SFDL-Swarm-Federated-Deep-Learning/issues/2#issuecomment-1238175358",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wkyd** [comment]
请问我在执行./swarm-learning/bin/run-apls后，提示：
Unable to find image 'hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/apls:0.3.0' locally
docker: Error response from daemon: Head "https://hub.myenterpriselicense.hpe.com/v2/hpe_eval/swarm-learning/apls/manifests/0.3.0": no basic auth credentials.
See 'docker run --help'.
我该怎么处理这个问题，谢谢！
