### ISSUE TITLE
Can you provide the code about the credibility weight algorithm？

### ISSUE THREAD

**Issue by octoberzzzzz** [CoderTylor/IoV-SFDL-Swarm-Federated-Deep-Learning#3]
I found the content in Section 3.1 and Section 3.2 could not be found in the provided code. Could you add more details?

**Comment by CoderTylor** [comment]
Hi October,

The credibility weights are calculated according to the robust and effectiveness value and could be found at the federated.py, it’s calculated at the edge and cloud server so not put it at the Swarm part end node.

Happy Chinese lunar new year.
Best wishes

Tylor
![image](https://user-images.githubusercontent.com/55383755/213927427-8f90edc2-1756-461b-b487-8b21f40b1174.png)
